from datetime import timedelta

DEFAULT_LOOKBACK_DAYS = 365
DEFAULT_NUM_PATHS = 5000
DEFAULT_HORIZON_WEEKS = 8

FREIGHT_API_BASE_URL = "https://your-freight-api.example.com"
FREIGHT_API_KEY = "YOUR_API_KEY"

FREIGHT_API_LANE_PARAM = "lane"
FREIGHT_API_START_PARAM = "start_date"
FREIGHT_API_END_PARAM = "end_date"

FREIGHT_API_DATE_FIELD = "date"
FREIGHT_API_VALUE_FIELD = "value"

MIN_DATA_POINTS = 30
MIN_PRICE = 1e-6
DAY_FRACTION = 1.0
