from datetime import timedelta

DEFAULT_LOOKBACK_DAYS = 365
DEFAULT_NUM_PATHS = 5000
DEFAULT_HORIZON_WEEKS = 8

MIN_DATA_POINTS = 10      # lowered to support monthly Excel data (~14 points)
MIN_PRICE = 1e-6
DAY_FRACTION = 1.0

TRADING_ECONOMICS_API_BASE_URL = "https://api.tradingeconomics.com"
TRADING_ECONOMICS_API_KEY = "guest:guest"
TRADING_ECONOMICS_CONTAINERIZED_SYMBOL = "CONTFREIGHT:COM"
TRADING_ECONOMICS_WCI_SYMBOL = "WORLDCONTAINER:COM"

CTS_FREE_CSV_PATH = "data/cts_global_price_index.csv"
CTS_DATE_COLUMN = "date"
CTS_VALUE_COLUMN = "value"

EXCEL_DATA_PATH = "data.xlsx"